### ISSUE TITLE
User has_many carts and user has a current_cart is confusing

### ISSUE THREAD

**Issue by aturkewi** [learn-co-curriculum/flatiron-store-project#10]
I frequently see students confused by how this lab is set up with has_many carts and has a current cart. The solution has it set up such that a User `belongs_to :current_cart, :class_name => "Cart"` and a User `has_many :carts`. There is also this Order model that is provided with the lab and never tested or referenced. 

I want to redo some tests for this lab so that when a user checkouts out, their cart is emptied and converted into an order (or something like that). 

If it's preferable for the lab to remain as is though, please let me know.

@PeterBell @pletcher @jmburges

**Comment by pletcher** [comment]
That sounds like a reasonable thing to do to me.

I think the relationship between User and current_cart is okay, if a bit confusing for new users -- it makes sense to keep the foreign key on the users table to me.

**Comment by bhollan** [comment]
Also, the spec check that checks that a `line_item` has a default of 1 should probably be re-done:

```
@line_item = @item.line_items.create(quantity: 1, cart: @cart)

...

it 'has a quantity, default 1' do
  expect(@line_item.quantity).to eq(1)
end
```

It seems to me that it's not actually testing what it says it is.  The `quantity: 1` should be removed from the `create` statement, right?

**Comment by bhollan** [comment]
There also seems to be no test or README info to match the requirement in the sidebar thing: "Non logged in users can see all items with available inventory".

**Comment by PeterBell** [comment]
Hey @aturkewi want to put this in your backlog as a curriculum issue?

**Comment by aturkewi** [comment]
Got it!

**Comment by drakeltheryuujin** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
issue #28. 

We will add this to our internal work queue. We are in the process of updating
the materials in this section and will be rewriting this lesson to address the
current issues. We'll be taking all of this information into consideration in
upcoming releases of this curriculum.

We're closing this issue but invite you to follow the progress.

Thanks for contributing!
