### ISSUE TITLE
Maybe it's on purpose, but the specs/overall structure of this project are a mess.

### ISSUE THREAD

**Issue by gj** [learn-co-curriculum/flatiron-store-project#14]
Among the files that come with a fresh fork of the project, I deleted two controllers, a model, three views, two routes (entirely, and I pared down the scope of two additional routes), and a migration, and the specs all still pass.

Additionally, there are a lot of mildly annoying things to fix w/in the provided code, such as the `!!@cart` conditional in `views/layouts/_header`, the references to `current_cart` instead of `@cart` on the `views/carts/show` page, and the spec test's preference for `Sign up` and `Sign out` but `sign in` instead of `Sign in`.

I get that dropping into unfamiliar, subpar code is a necessary skill to gain as a developer, and if that's the intention here, okay. But as the penultimate Rails project, this just felt like a big letdown. Would've been simultaneously a lot more difficult _and_ a lot less annoying if I'd been tasked with building everything from the ground up.

**Comment by gj** [comment]
cc: @Lukeghenco

**Comment by Lukeghenco** [comment]
@gj did you set up a PR for this?

**Comment by gj** [comment]
@Lukeghenco what, I have to do everything around here? :joy:

**Comment by drakeltheryuujin** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
issue #28. 

We will add this to our internal work queue. We are in the process of updating
the materials in this section and will be rewriting this lesson to address the
current issues. We'll be taking all of this information into consideration in
upcoming releases of this curriculum.

We're closing this issue but invite you to follow the progress.

Thanks for contributing!
