### ISSUE TITLE
Get rid of devise requirement.

### ISSUE THREAD

**Issue by SYoung82** [learn-co-curriculum/flatiron-store-project#17]
The requirement to use devise in this project seems like overkill to me.  The project requires a simple login/logout flow but tests will not pass without using devise.  Devise seems like trying to set a nail with a sledgehammer in this case, too much tool for the job.  I also feel that most students will learn more and gain a better understanding of authentication by not requiring devise be used.

I attempted to roll my own authentication with a session controller, etc... but tests would not pass.  Eventually Learn experts directed me to use devise to implement what I had already implemented without.  I understand that the directions state to use devise to set up the project.  Perhaps if you would like to require the student to use devise, make them include a Github Oauth authorization flow.

**Comment by drakeltheryuujin** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
issue #28. 

We will add this to our internal work queue. We are in the process of updating
the materials in this section and will be rewriting this lesson to address the
current issues. We'll be taking all of this information into consideration in
upcoming releases of this curriculum.

We're closing this issue but invite you to follow the progress.

Thanks for contributing!
