### ISSUE TITLE
does not display "Add To Cart" button passes when it shouldn't

### ISSUE THREAD

**Issue by mdo5004** [learn-co-curriculum/flatiron-store-project#19]
spec/features/store_home_feature_spec.rb

Item list not logged in 'does not display "Add To Cart" button' passes when it should fail. Using my site on localhost:3000 displays the Add To Cart buttons when I'm not signed in, but it passes this test.

**Comment by drakeltheryuujin** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
issue #28. 

We will add this to our internal work queue. We are in the process of updating
the materials in this section and will be rewriting this lesson to address the
current issues. We'll be taking all of this information into consideration in
upcoming releases of this curriculum.

We're closing this issue but invite you to follow the progress.

Thanks for contributing!
