### ISSUE TITLE
Factory Missing

### ISSUE THREAD

**Issue by skmcloughlin** [learn-co-curriculum/flatiron-store-project#20]
spec/factories/user.rb is blank
FactoryGirl.create(:user) needs to be added to seed file as well.

**Comment by drakeltheryuujin** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
issue #28. 

We will add this to our internal work queue. We are in the process of updating
the materials in this section and will be rewriting this lesson to address the
current issues. We'll be taking all of this information into consideration in
upcoming releases of this curriculum.

We're closing this issue but invite you to follow the progress.

Thanks for contributing!
