### ISSUE TITLE
 TZInfo::DataSourceNotFound errors for Windows

### ISSUE THREAD

**Issue by dande313** [learn-co-curriculum/flatiron-store-project#21]
Tried all the steps on https://github.com/tzinfo/tzinfo/wiki/Resolving-TZInfo::DataSourceNotFound-Errors,
including adding "gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw]", etc.
Also added it to the config file.  Can't run a server, or even rake db:migrate.

**Comment by drakeltheryuujin** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
issue #28. 

We will add this to our internal work queue. We are in the process of updating
the materials in this section and will be rewriting this lesson to address the
current issues. We'll be taking all of this information into consideration in
upcoming releases of this curriculum.

We're closing this issue but invite you to follow the progress.

Thanks for contributing!
