### ISSUE TITLE
Question: A bunch of us are on J's Study Group for Flatiron Store: missing clues for migration content

### ISSUE THREAD

**Issue by MiriamPeskowitz** [learn-co-curriculum/flatiron-store-project#27]
What's confusing for everyone, and for J too, is that neither the directions nor the specs seem to give any indication of what should be in the migrations, and how the scheme should look. Is this an oversight, or something that's fallen out of the text and file structure? Are we missing something? 

Thanks, 

Miriam

**Comment by drakeltheryuujin** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
issue #28. 

We will add this to our internal work queue. We are in the process of updating
the materials in this section and will be rewriting this lesson to address the
current issues. We'll be taking all of this information into consideration in
upcoming releases of this curriculum.

We're closing this issue but invite you to follow the progress.

Thanks for contributing!
