### ISSUE TITLE
Two Dependencies cause errors and are 110% not needed to get all tests to pass

### ISSUE THREAD

**Issue by genericlady** [learn-co-curriculum/flatiron-store-project#8]
capybara-webkit on ruby 2.3.0 using OSX Elcapitan without that openssl package as a depdency. My OSX only uses the new encryption and all the labs that had Gem's that required openssl i simply removed and finished the labs.

here is the debug when i try to bundle with capybara-webkit not commented out

```
/Users/yonk/.rvm/rubies/ruby-2.3.0/bin/ruby -r ./siteconf20160419-7773-19sk1u1.rb extconf.rb
sh: qmake: command not found
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
    --with-opt-dir
    --with-opt-include
    --without-opt-include=${opt-dir}/include
    --with-opt-lib
    --without-opt-lib=${opt-dir}/lib
    --with-make-prog
    --without-make-prog
    --srcdir=.
    --curdir
    --ruby=/Users/yonk/.rvm/rubies/ruby-2.3.0/bin/$(RUBY_BASE_NAME)
    --with-gl-dir
    --without-gl-dir
    --with-gl-include
    --without-gl-include=${gl-dir}/include
    --with-gl-lib
    --without-gl-lib=${gl-dir}/lib
    --with-zlib-dir
    --without-zlib-dir
    --with-zlib-include
    --without-zlib-include=${zlib-dir}/include
    --with-zlib-lib
    --without-zlib-lib=${zlib-dir}/lib
Command 'qmake LIBS\ \+\=\ -L/usr/local/opt/libyaml/lib\ -L/usr/local/opt/readline/lib\ -L/usr/local/opt/libksba/lib\ -L/usr/local/opt/openssl/lib' not available

extconf failed, exit code 1
```

I was getting an error with airbrake as well but can't replicate.  I removed both gems from my Gemfile and everything is fine.  There's also a production block which is odd.  Since this project isn't being launched.  It's almost like the educator just copy and pasted a gemfile.  That's like teaching your students bad habits.  Food for thought.  peace and love <3

**Comment by pletcher** [comment]
Thanks for this -- fixed with https://github.com/learn-co-curriculum/flatiron-store-project/commit/4548f1acff932712aea1541e1140425f2061394f

**Comment by genericlady** [comment]
Hey one thing I failed to mention is that the rails gem shouldn't have a version because 4.2 will make the whole thing crash if you run `bundle update`

**Comment by pletcher** [comment]
I just ran `bundle update` -- didn't see any issues. What error are you getting?
